images:
- name: osixia/openldap:1.3.0
  desc: ldap
  count: 1
  start_on_create: True
  sub_domain: ldap 
  
#- name: gotechnies/alpine-ssh:latest
#  desc: alpine
#  count: 100
#  start_on_create: True
#  sub_domain: alpine.research1 
#  startup_script: create_users_alpine.sh alpine_users.csv

#- name: rastasheep/ubuntu-sshd
#  desc: ubuntu
#  count: 1
#  start_on_create: True
#  sub_domain: ubuntu.research1 
#  startup_script: create_users.sh users.csv


#- name: mcr.microsoft.com/mssql/server:2017-latest
#  desc: SQL Server
#  count: 10
#  start_on_create: True
#  sub_domain: mssql.research1 
#  env_variables:
#  - 'ACCEPT_EULA=Y'
#  - 'SA_PASSWORD=yourStrong(!)Password'

#- name: iliyan/docker-nginx-sshd:latest
#  desc: research
#  count: 1
#  start_on_create: True
#  sub_domain: www.research1 

#- name: jdeathe/centos-ssh-mysql:latest
#  desc: research
#  count: 1
#  start_on_create: True
#  sub_domain: mysql.research1 

#- name: osixia/openldap:1.3.0
#  desc: research
#  count: 1 
#  start_on_create: True
#  sub_domain: ldap.research1 

naming:
  allowable_host_chars: '[^a-z0-9]'
  max_host_len: 20
  min_host_len: 2
  word_file: en.txt

container_network:
  address: 10.0.0.0
  name: clab
  domain: acmehosting.com
  
firewall:
  queue_num: "0"
  interface: lo
  proxy_port: 5996
  chain_name: CLAB
  read_buffer: 1024

container_manager:
  client_pool: 25
  max_containers: 40
  poll_time: 1
  expire_after: 20
