images:
- name: gotechnies/alpine-ssh:latest
  desc: research
  count: 10
  start_on_create: true
  sub_domain: alpine.research1 
  startup_script: create_users_alpine.sh alpine_users.csv

#- name: postgres:latest
#  desc: Postgres
#  count: 25
#  start_on_create: True
#  sub_domain: postgres.db 
#  env_variables:
#  - 'POSTGRES_PASSWORD=mysecretpassword'

#- name: mcr.microsoft.com/mssql/server:2017-latest
#  desc: SQL Server
#  count: 25
#  sub_domain: mssql.db 
#  start_delay: 2
#  env_variables:
#  - 'ACCEPT_EULA=Y'
#  - 'SA_PASSWORD=yourStrong(!)Password'

#- name: mysql:latest
#  desc: MySQL
#  count: 10
#  sub_domain: mysql.db 
#  start_delay: 2
#  env_variables:
#  - 'MYSQL_ROOT_PASSWORD=my-secret-pw'

naming:
  allowable_host_chars: '[^a-z0-9]'
  max_host_len: 20
  min_host_len: 2
  word_file: en.txt

container_network:
  address: 10.0.0.0
  name: clab
  domain: acmehosting.com
  
firewall:
  queue_num: 0
  interface: lo
  proxy_port: 5996
  chain_name: CLAB
  read_buffer: 1024
  instances: 2

container_manager:
  client_pool: 25
  max_containers: 20
  poll_time: 1
  expire_after: 5
  stop_per_iteration: 1
