images:
- name: gotechnies/alpine-ssh:latest
  desc: research
  count: 1 
  start_on_create: false
  sub_domain: research1 

- name: iliyan/docker-nginx-sshd:latest
  desc: research
  count: 1
  start_on_create: True
  sub_domain: www.research1 

- name: jdeathe/centos-ssh-mysql:latest
  desc: research
  count: 1
  start_on_create: True
  sub_domain: mysql.research1 

- name: osixia/openldap:1.3.0
  desc: research
  count: 1 
  start_on_create: True
  sub_domain: ldap.research1 

naming:
  allowable_host_chars: '[^a-z0-9]'
  max_host_len: 20
  min_host_len: 2
  word_file: en.txt

container_network:
  address: 10.0.0.0
  name: clab
  domain: acmehosting.com

network_handler:
  queue_num: "0"
  interface: ens33
  proxy_port: 5996
  chain_name: CLAB
